sudo: required

service:
  - docker

before_install:
  - openssl aes-256-cbc -K $encrypted_38940f9cddad_key -iv $encrypted_38940f9cddad_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com > install.sh
  - bash install.sh --disable-prompts
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components install kubectl --quiet
  - gcloud components update --quiet
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project multi-k8s-273919
  - gcloud config set compute/zone us-central1-c 
  - gcloud container clusters get-credentials first-k8s
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t alxga/k8s-client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run alxga/k8s-client-test npm test -- --coverage

#deploy:
#  provider: script
#  script: bash ./deploy.sh
#  on:
#    branch: master