sudo: required

service:
  - docker

before_install:
  - openssl aes-256-cbc -K $encrypted_38940f9cddad_key -iv $encrypted_38940f9cddad_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project multi-k8s-273919
  - gcloud config set compute/zone us-central1-c 
  - gcloud container clusters get-credentials multi-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t alxga/k8s-client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run alxga/k8s-client-test npm test -- --coverage