apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: fib-figuresfacts-me-tls
spec:
  secretName: fib-figuresfacts-me
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: fib.figuresfacts.me
  dnsNames:
    - fib.figuresfacts.me
  acme:
    config:
      - http01:
        ingressClass: nginx
        domains:
          - fib.figuresfacts.me
